/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuxchat.ui.client;

import com.sun.glass.events.KeyEvent;
import cuxchat.ChatClient;
import cuxchat.CuxMessage;
import cuxchat.commands.ClientCommands;
import cuxchat.utils.CuxLogger;
import cuxchat.utils.CuxMessenger;
import cuxchat.utils.CuxStringEncrypter;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author mihaicux
 */
public class ClientChatUI extends javax.swing.JFrame {

    public ChatClient client;
    public String endpoint;
    public HTMLEditorKit kit;
    public HTMLDocument doc;
    
    public boolean isBold;
    public boolean isItalic;
    public boolean isUnderline;
    public int fontSize;
    public String foregroundColor;
    public String backgroundColor;
    
    
    /**
     * Creates new form ClientUI
     */
    public ClientChatUI(ChatClient client) {
        this.client = client;
        initComponents();
        setDefaultFont();
    }

    public void setDefaultFont(){
        isBold = false;
        isItalic = false;
        isUnderline = false;
        fontSize = 12;
        foregroundColor = "000000";
        backgroundColor = "ffffff";
        jComboBox1.setSelectedIndex(1);
        boldBtn.setSelected(false);
        italicBtn.setSelected(false);
        underlineBtn.setSelected(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commandText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputTxt = new javax.swing.JTextPane();
        boldBtn = new javax.swing.JToggleButton();
        italicBtn = new javax.swing.JToggleButton();
        underlineBtn = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        avatar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        commandText.setColumns(20);
        commandText.setRows(5);
        commandText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                commandTextKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(commandText);

        outputTxt.setEditable(false);
        kit = new HTMLEditorKit();
        doc = new HTMLDocument();
        outputTxt.setEditorKit(kit);
        outputTxt.setDocument(doc);
        outputTxt.setEditable(false);
        jScrollPane3.setViewportView(outputTxt);

        boldBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        boldBtn.setText("B");
        boldBtn.setToolTipText("Bold");
        boldBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boldBtnItemStateChanged(evt);
            }
        });

        italicBtn.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        italicBtn.setText("I");
        italicBtn.setToolTipText("Italic");
        italicBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                italicBtnItemStateChanged(evt);
            }
        });

        Map<TextAttribute, Integer> fontAttributes = new HashMap<TextAttribute, Integer>();
        fontAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        java.awt.Font boldUnderline = new java.awt.Font("Ubuntu", 0, 15).deriveFont(fontAttributes);
        underlineBtn.setFont(boldUnderline);
        underlineBtn.setText("U");
        underlineBtn.setToolTipText("Underline");
        underlineBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                underlineBtnItemStateChanged(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "12", "14", "16" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Size");

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuxchat/images/background.png"))); // NOI18N
        jButton2.setToolTipText("Choose background color");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuxchat/images/foreground.png"))); // NOI18N
        jButton3.setToolTipText("Choose foreground color");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(italicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boldBtn)
                    .addComponent(italicBtn)
                    .addComponent(underlineBtn)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuxchat/images/avatar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(avatar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset font");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Close");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closeWindow(){
        this.dispose();
        this.setVisible(false);
        client.clientBox.boxes.remove(client.nume);
    }
    
    public void sendPrivateMessage(){
        String cmd = commandText.getText().trim();
        String style = "font-size: "+fontSize+"px; background: #"+backgroundColor+"; color: #"+foregroundColor+";";
        if (isBold){
            style += "font-weight: bold;";
        }
        if (isItalic){
            style += "font-style: italic;";
        }
        if (isUnderline){
            style += "text-decoration: underline;";
        }
        cmd = "<span style='"+style+"'>"+cmd+"</span>";
        try {
            CuxStringEncrypter desEncrypter = new CuxStringEncrypter();
            CuxMessage msg = new CuxMessage("MESSAGE");
            msg.put("message", "/msg "+endpoint+" "+cmd);
            this.client.out.out.writeUTF(desEncrypter.encrypt(msg.toString()));
            commandText.setText("");
            commandText.setCaretPosition(0);
            kit.insertHTML(doc, doc.getLength(), "you : "+cmd, 0, 0, null);
            outputTxt.setCaretPosition(doc.getLength());
            commandText.requestFocus();
        } catch (IOException ex) {
            //                ex.printStackTrace();
            ClientCommands.updateLog(ex.getMessage());
            CuxLogger.getInstance().logException2(ex);
        } catch (BadLocationException ex) {
            ClientCommands.updateLog(ex.getMessage());
            CuxLogger.getInstance().logException2(ex);
        }
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeWindow();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        closeWindow();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendPrivateMessage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void commandTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commandTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (evt.isControlDown()){ // new line
                commandText.append("\n");
            }
            else{
                sendPrivateMessage();
            }
        }
    }//GEN-LAST:event_commandTextKeyPressed

    private void boldBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boldBtnItemStateChanged
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED){
            isBold = true;
        } else if(evt.getStateChange()==java.awt.event.ItemEvent.DESELECTED){
            isBold = false;
        }
    }//GEN-LAST:event_boldBtnItemStateChanged

    private void italicBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_italicBtnItemStateChanged
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED){
            isItalic = true;
        } else if(evt.getStateChange()==java.awt.event.ItemEvent.DESELECTED){
            isItalic = false;
        }
    }//GEN-LAST:event_italicBtnItemStateChanged

    private void underlineBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_underlineBtnItemStateChanged
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED){
            isUnderline = true;
        } else if(evt.getStateChange()==java.awt.event.ItemEvent.DESELECTED){
            isUnderline = false;
        }
    }//GEN-LAST:event_underlineBtnItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == 1){ // new element
            fontSize = Integer.parseInt(evt.getItem().toString());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public static Color hex2Rgb(String colorStr) {
        return new Color(
                Integer.valueOf( colorStr.substring( 0, 2 ), 16 ),
                Integer.valueOf( colorStr.substring( 2, 4 ), 16 ),
                Integer.valueOf( colorStr.substring( 4, 6 ), 16 ) );
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Color bg = JColorChooser.showDialog(this, "Choose background color", hex2Rgb(backgroundColor));
        if(bg != null){
            backgroundColor = Integer.toHexString(bg.getRGB()).substring(2);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Color fg = JColorChooser.showDialog(this, "Choose foreground color", hex2Rgb(foregroundColor));
        if(fg != null){
            foregroundColor = Integer.toHexString(fg.getRGB()).substring(2);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setDefaultFont();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(ClientChatUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File myFile = fc.getSelectedFile();
            byte [] mybytearray  = new byte [(int)myFile.length()];
            FileInputStream fis;
            try {
                fis = new FileInputStream(myFile);
                fis.read(mybytearray);
                fis.close();
                int kbyte32 = 1024*32;
                
                Double chunks = Math.ceil(mybytearray.length / kbyte32);
                if (chunks.intValue() < 1)
                    chunks = Double.parseDouble("1");
                
                for (int i = 0; i < chunks; i++){
                    int start = kbyte32 * i;
                    int end   = kbyte32 * (i+1);
                    if (end > mybytearray.length) end = mybytearray.length;
                    System.out.println(start+", "+end+" : "+chunks + "[ "+mybytearray.length+" ]");
                    CuxMessage msg = new CuxMessage("FILE");
                    msg.put("file_to", endpoint);
                    msg.put("file_name", myFile.getName());
                    msg.put("file_type", ClientRegisterUI.getFileExtension(myFile));
                    msg.put("file_chunks", chunks.intValue());                
                    msg.put("file_chunk_no", i+1);
                    msg.put("file_part", Arrays.copyOfRange(mybytearray, start, end));
                    msg.put("file_bytes", mybytearray.length);
                    CuxStringEncrypter desEncrypter = new CuxStringEncrypter();
                    this.client.out.out.writeUTF(desEncrypter.encrypt(msg.toString()));
                }
                
            } catch (FileNotFoundException ex) {
                CuxLogger.getInstance().logException2(ex);
            } catch (IOException ex) {
                CuxLogger.getInstance().logException2(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel avatar;
    private javax.swing.JToggleButton boldBtn;
    public javax.swing.JTextArea commandText;
    private javax.swing.JToggleButton italicBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextPane outputTxt;
    private javax.swing.JToggleButton underlineBtn;
    // End of variables declaration//GEN-END:variables
}
